name: cocoa-farm-app
services:
- name: web
  github:
    repo: your-username/your-repo
    branch: main
  run_command: flutter pub get && flutter build web && cd build/web && python3 -m http.server 8080
  source_dir: /
  environment_slug: flutter-1
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /